apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: wordpress
    type: database
spec:
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  #clusterIP: None